### ISSUE TITLE
Completions suddenly not working after last update

### ISSUE THREAD

**Issue by FeBe95** [ryboe/CSS3#129]
Good day sir,

the CSS completions don't seem to work anymore.
I get the following error when I start Sublime Text or disable & re-enable the CSS3 package:

```Python
...
reloading plugin CSS3.css3_completions
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Installed Packages\CSS3.sublime-package\css3_completions.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Installed Packages\CSS3.sublime-package\completions/properties.py", line 1806, in <module>
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Installed Packages\CSS3.sublime-package\completions/properties.py", line 1802, in sort_and_uniq_completions
TypeError: unhashable type: 'list'
reloading plugin CSS3.rgb_to_hex
...
```

**Comment by ganin2** [comment]
same

**Comment by ryboe** [comment]
Thank you for reporting the issue! Sorry I let this one slip by. I have CI checks for the syntax definition, but nothing for completions. I don't know how to add a check for this 🤔

The fix is pushed and should land on Package Control within an hour or so. Sorry for the trouble.
